BEGIN TRANSACTION;
CREATE TABLE "staff" (
	`id`	INTEGER,
	`name`	TEXT NOT NULL,
	`type`	TEXT NOT NULL DEFAULT 'STAFF',
	`office_space`	TEXT,
	PRIMARY KEY(`id`)
) WITHOUT ROWID;
CREATE TABLE "offices" (
	`id`	INTEGER,
	`name`	TEXT NOT NULL,
	`type`	TEXT NOT NULL DEFAULT 'OFFICE',
	`occupants`	TEXT,
	`MAX_CAPACITY`	INTEGER NOT NULL DEFAULT 6,
	PRIMARY KEY(`id`)
) WITHOUT ROWID;
CREATE TABLE "livingspaces" (
	`id`	INTEGER,
	`name`	TEXT NOT NULL,
	`type`	TEXT NOT NULL DEFAULT 'LIVING',
	`occupants`	TEXT,
	`MAX_CAPACITY`	INTEGER NOT NULL DEFAULT 4,
	PRIMARY KEY(`id`)
);
CREATE TABLE "fellows" (
	`id`	INTEGER,
	`name`	TEXT NOT NULL,
	`type`	TEXT NOT NULL DEFAULT 'FELLOW',
	`office_space`	TEXT,
	`living_space`	TEXT,
	`accommodation`	TEXT NOT NULL DEFAULT 'N',
	PRIMARY KEY(`id`)
) WITHOUT ROWID;
COMMIT;
